apiVersion: v1
kind: Service
metadata:
  name: flask-s3-app-service
spec:
  selector:
    app: flask-s3-app
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 31200
      targetPort: 5000
  type: NodePort
